import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import Database from "better-sqlite3";
import { WebSocketServer, WebSocket } from "ws";
import { createServer } from "http";
import axios from "axios";
import cookieParser from "cookie-parser";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const httpServer = createServer(app);
  const PORT = 3000;

  // Database setup
  const db = new Database("saintsal_builder.db");
  db.exec(`
    CREATE TABLE IF NOT EXISTS messages (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      text TEXT NOT NULL,
      sender TEXT NOT NULL,
      timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS projects (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      config TEXT NOT NULL,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
  `);

  app.use(express.json());
  app.use(cookieParser());

  // GitHub OAuth Routes
  app.get("/api/auth/github", (req, res) => {
    const clientId = process.env.GITHUB_CLIENT_ID;
    if (!clientId) return res.status(500).json({ error: "GitHub Client ID not configured" });
    
    const redirectUri = `${req.protocol}://${req.get('host')}/api/auth/github/callback`;
    const url = `https://github.com/login/oauth/authorize?client_id=${clientId}&redirect_uri=${redirectUri}&scope=repo,user`;
    res.json({ url });
  });

  app.get("/api/auth/github/callback", async (req, res) => {
    const { code } = req.query;
    try {
      const response = await axios.post("https://github.com/login/oauth/access_token", {
        client_id: process.env.GITHUB_CLIENT_ID,
        client_secret: process.env.GITHUB_CLIENT_SECRET,
        code,
      }, {
        headers: { Accept: "application/json" }
      });

      const { access_token } = response.data;
      if (!access_token) throw new Error("No access token returned");

      res.cookie("github_token", access_token, { httpOnly: true, secure: true, sameSite: 'none' });
      res.send(`
        <html>
          <body>
            <script>
              window.opener.postMessage({ type: 'GITHUB_AUTH_SUCCESS' }, '*');
              window.close();
            </script>
            <p>Authentication successful. Closing window...</p>
          </body>
        </html>
      `);
    } catch (error) {
      console.error("GitHub Auth Error:", error);
      res.status(500).send("Authentication failed");
    }
  });

  app.get("/api/auth/github/status", (req, res) => {
    res.json({ connected: !!req.cookies.github_token });
  });

  app.post("/api/github/push", async (req, res) => {
    const token = req.cookies.github_token;
    if (!token) return res.status(401).json({ error: "Not connected to GitHub" });

    const { repoName, files, description } = req.body;
    
    try {
      const headers = { Authorization: `token ${token}`, Accept: "application/vnd.github.v3+json" };
      
      // 1. Get user info
      const userRes = await axios.get("https://api.github.com/user", { headers });
      const username = userRes.data.login;

      // 2. Create or get repo
      let repo;
      try {
        const repoRes = await axios.get(`https://api.github.com/repos/${username}/${repoName}`, { headers });
        repo = repoRes.data;
      } catch (e) {
        const createRes = await axios.post("https://api.github.com/user/repos", {
          name: repoName,
          description: description || "Generated by SaintSal™ Studio",
          auto_init: true
        }, { headers });
        repo = createRes.data;
      }

      // 3. Push files (Simplified: one by one for now)
      for (const [path, content] of Object.entries(files)) {
        let sha;
        try {
          const fileRes = await axios.get(`https://api.github.com/repos/${username}/${repoName}/contents/${path}`, { headers });
          sha = fileRes.data.sha;
        } catch (e) {}

        await axios.put(`https://api.github.com/repos/${username}/${repoName}/contents/${path}`, {
          message: `Update ${path} via SaintSal™`,
          content: Buffer.from(content as string).toString("base64"),
          sha
        }, { headers });
      }

      res.json({ success: true, url: repo.html_url });
    } catch (error: any) {
      console.error("GitHub Push Error:", error.response?.data || error.message);
      res.status(500).json({ error: "Failed to push to GitHub" });
    }
  });

  // API Routes
  app.get("/api/messages", (req, res) => {
    const messages = db.prepare("SELECT * FROM messages ORDER BY timestamp ASC").all();
    res.json(messages);
  });

  app.get("/api/projects", (req, res) => {
    const projects = db.prepare("SELECT * FROM projects ORDER BY updated_at DESC").all();
    res.json(projects);
  });

  app.post("/api/projects", (req, res) => {
    const { name, config } = req.body;
    const info = db.prepare("INSERT INTO projects (name, config) VALUES (?, ?)").run(name, JSON.stringify(config));
    res.json({ id: info.lastInsertRowid, name, config });
  });

  // WebSocket Server
  const wss = new WebSocketServer({ server: httpServer });

  wss.on("connection", (ws) => {
    console.log("New client connected");

    ws.on("message", (data) => {
      const message = JSON.parse(data.toString());
      
      if (message.type === "chat") {
        const info = db.prepare("INSERT INTO messages (text, sender) VALUES (?, ?)").run(message.text, message.sender);
        const savedMessage = { id: info.lastInsertRowid, ...message, timestamp: new Date().toISOString() };
        
        // Broadcast to all clients
        wss.clients.forEach((client) => {
          if (client.readyState === WebSocket.OPEN) {
            client.send(JSON.stringify({ type: "chat", payload: savedMessage }));
          }
        });
      }

      if (message.type === "build") {
        // Broadcast build updates
        wss.clients.forEach((client) => {
          if (client.readyState === WebSocket.OPEN) {
            client.send(JSON.stringify({ type: "build", payload: message.payload }));
          }
        });
      }
    });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  httpServer.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
